modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/techarium/issues"

[[mods]]
modId = "techarium"
version = "${version}"
displayName = "Techarium"
displayURL = "https://modrinth.com/mod/techarium"
logoFile = "icon.png"
authors = "Alex Nijjar, Cybronaut, Ycar"
credits = ""
description = "Cool tech mod"

[[dependencies.techarium]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techarium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techarium]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techarium]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techarium]]
modId = "botarium"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techarium]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2.2,)"
ordering = "NONE"
side = "BOTH"