modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="techarium"
version="${file.jarVersion}"
displayName="Techarium"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="multiloader.png"
#credits="Thanks for this example mod goes to Java"
authors="Techarium team"
description='''
ditto
'''
[[dependencies.techarium]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.techarium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
